services:
  golang:
    image: system_of_crush:latest
    build: ./
    ports: 
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: system_of_crush
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./internal/database/init_db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5433:5432

  pgadmin4:
    image: elestio/pgadmin:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "8081:8080"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8084:8080"
    environment:
      - SWAGGER_JSON=/api/openapi.yaml
    volumes:
      - ./docs:/api