services:
  golang:
    build: ./
    ports: 
      - "8080:8080"
    depends_on:
      - postgres


  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: system_of_crush
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: *password*
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./internal/database/init_db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5433:5432

  pgadmin4:
    image: elestio/pgadmin:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: *email*
      PGADMIN_DEFAULT_PASSWORD: *password*
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "8081:8080"
    volumes:
      - ./servers.json:/pgadmin4/servers.json